### ISSUE TITLE
really?

### ISSUE THREAD

**Issue by mcgi5sr2** [SubstratumResources/platform_packages_apps_ExactCalculator#3]
packages/apps/ExactCalculator/res/values/projekt_dimens.xml:17: error: Error parsing XML: XML or text declaration not at start of entity

**Comment by KreAch3R** [comment]
Please submit all necessary changes to our gerrit: https://substratum.review/#/q/status:open

(And yeah, this should show how many people care for ExactCalculator in their roms)

**Comment by mcgi5sr2** [comment]
ok sorry was just super annoyed as it happens at like 99% of build process
